Resolución de kata "Mount the Bowling Pins"
TechnoLatinas/coding-dojo pull request #1
Opened 2021-09-18 18:39 UTC by cecivieira

Kata hecha durante el coding dojo del 18 set. 2021 por @keizar76 , @aleepsy y @cecivieira

2021-09-18 18:42 UTC, aleepsy commented
¡Súper bien trabajado, chicas!
¡Felicidades! 🥳

2021-09-20 16:57 UTC, MarceStarlet requested changes
Hola Ana, podrías modificar el PR para que se apegue a las normas de colaboración del repo?
Las puedes encontrar en el [README](https://github.com/TechnoLatinas/coding-dojo) en la sección de "**Cómo colaborar con el código**", te dejo el extracto aquí también.

Cómo colaborar con el código
¿Fuiste parte de alguna edición de Coding Dojo con Technolatinas y deseas colaborar?

Puedes subir tu solución en la carpeta del año, el evento en que participaste y el lenguaje de programación en que lo implementaste. Crea una carpeta con el nombre solucion-<tu nombre> y dentro agrega tu código, si no existe la carpeta del lenguaje crea una nueva.

Recuerda poner tus datos en un comentario dentro de tu código para poder identificarte.

Ejemplo:
```
coding-dojo
> 2021
  > dia-de-la-programadora
    > java
      > solucion-marcela-sena
        > tuArchivoVaAqui
```

2021-09-29 17:43 UTC, cecivieira commented
Claro @MarceStarlet 
Mira si ahora cuadra en las normas de colaboración.

2021-09-29 17:46 UTC, MarceStarlet approved these changes
Está perfecto, gracias y buen trabajo 👍

2021-10-06 16:51 UTC, algorithmich commented
Tal vez debamos hacer merge al PR? @MarceStarlet

2021-10-07 19:57 UTC, merged